### ISSUE TITLE
Zotex: Open in Zotero

### ISSUE THREAD

**Issue by ForeUP** [RayKr/zotex#1]
Great work!

But, I don't quite understand this `Zotex: Open in Zotero` command. When I use it, it only opens Zotero, but doesn't indicate the corresponding entry.

Looking forward to your response.

**Comment by raykr** [comment]
You need to place the cursor on citekey and then run Zotex: Open in Zotero, which will open the corresponding entry in Zotero. Did you not place the cursor on citekey?

**Comment by raykr** [comment]
I have also reproduced the problem and am investigating the cause.

**Comment by ForeUP** [comment]
Thanks

**Comment by raykr** [comment]
I found that this problem is also caused by special characters `-` and `_` in the citekey, which leads to incorrect recognition. I have fixed this issue. Now Zotex supports citekeys with special characters, although I do not recommend using them. Just upgrade Zotex to v1.0.8 to solve it.
