### ISSUE TITLE
Bug! Zotex: Add Citation

### ISSUE THREAD

**Issue by ForeUP** [RayKr/zotex#2]
When a document has a **Cite Key** like `Suh_2018_Part-aligned`, `-` and the one after it cannot be inserted automatically, which means that any document with a **Cite Key** like this can only be typed manually inside `\cite{}`.

**Comment by raykr** [comment]
Do you mean that your citekey can't be imported automatically if it contains a `_` `-` type of ligature? The BBT rules I'm using don't use connectors, so I haven't encountered this situation before, I'll try.

**Comment by ForeUP** [comment]
Only an import failure will occur if the citekey contains `-`, whereas the presence of `_` will not cause any failures. The BBT rules I'm using is `[auth]_[year]_[Title:skipwords:select,1,1]`, which selects the first word of the paper title. Therefore, if a paper's title starts with a word that includes "-", it will result in a failed import of the citekey.

**Comment by raykr** [comment]
OK, I see this bug and have fixed it. Thanks for your report. Just update Zotex to v1.0.7 to solve it.
